language: node_js

node_js: lts/*

if: tag IS blank

install:
  - npm ci

stages:
  - test
  - benchmark

jobs:
  include:
    - stage: test
      script:
        - npm test
    - stage: benchmark
      script:
        - npm run benchmark:parseArray
