import fs from 'fs'

const parseArrayContent = fs.readFileSync('public/parseArray.js').toString()

const optimizeParseArrayContent = (content) => {
  return (
    `/* Do not modify by hand. This file has been automatically generated by scripts/createOptimizedParseArray.js. */\n\n` +
    content
      .replaceAll(
        'State.AfterEscape3AfterSemicolon2',
        '/* AfterEscape3AfterSemicolon2 */ 6',
      )
      .replaceAll(
        'State.AfterEscape3AfterSemicolon',
        '/* AfterEscape3AfterSemicolon */ 5',
      )
      .replaceAll('State.AfterEscape4', '/* AfterEscape4 */ 4')
      .replaceAll('State.AfterEscape3', '/* AfterEscape3 */ 3')
      .replaceAll('State.AfterEscape2', '/* AfterEscape2 */ 2')
      .replaceAll('State.AfterEscape1', '/* AfterEscape1 */ 1')
      .replaceAll('State.TopLevelContent', '/* TopLevelContent */ 0')
  )
}

const optimizedContent = optimizeParseArrayContent(parseArrayContent) //?

fs.writeFileSync('./public/optimizedParseArray.js', optimizedContent)
